name: Syntax-check models

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  check:
    name: Syntax-check models
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Download TLA⁺
        run: wget https://nightly.tlapl.us/dist/tla2tools.jar
      - name: Check models
        run: .github/workflows/check.sh
